### ISSUE TITLE
Estimate time for site updates

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/cocina214.com-archive-hugo#1]
https://cocina214.com

Please estimate the following client-requested changes. These look pretty straightforward. Seems like we wouldn't need to change the CSS tooling (it's utility, but not tailwind), but we would have bring Hugo up-to-date, which could take a few hours. 
 
**Home Page:**
 
We need a color update on this page.
Replace the “Mexican Kitchen and Bar” with a new picture – the pic with the mural in the main lobby
Want a new picture to the right of the “Upcoming Events” section
 
**About  Page:**
 
We need a color update on this page.
Replace the main picture with a new picture – not sure which one yet?
 
**Loyalty  Page:**
 
We need a color update on this page.
Fix the “Download Info card” with the new card
 
**Dine  Page:**
 
We need a color update on this page.
Update the hero pics with new interior ones
Need a new pic next to the “Dine with us” Info
Need a new pic next to the “Order Online” info
Need a new pic next to the “Catering” info
Need a new pics next to the “BOOK YOUR PRIVATE PARTY OR CATERING”
Fix the back-end of the “BOOK YOUR PRIVATE PARTY OR CATERING” It should just be Winter Park location and maybe have a separate Private Dining and Catering sections, so we can promote them differently with different pcs?
 
**News  Page:**
 
We need a color update on this page.
We can Hide the “press” section on this page. We don’t keep it up to date. Is there a way to keep the data but just hide it, I case we want to go back to updating it?
 
**Shop  Page:**
 
We need a color update on this page.
Can we change this to read “online ordering” instead of shop?
For now we want to hide the t-shirts and tumblers. We just want to keep the order online “Order Now” section and the gift cards.
 
**Contact  Page:**
 
We need a color update on this page.
Update the food pic on this page too.

**Comment by AdamChlan** [comment]
@budparr I agree that the content changes are straightforward. Thinking 3-4 hours should be fine. Then I suppose a few hours for the Hugo update?

**Comment by budparr** [comment]
Thanks!
