### ISSUE TITLE
Update CMS

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/cocina214.com-archive-hugo#13]
I think some of #7 can be handled by giving the client improved access to certain elements.

> In Forestry, under Pages>Dine>Events it is split up with a “Winter park” photo and text and a “Daytona Beach” photo and text. We sold the Daytona location and want to rework the website without it. On the actual website you don’t see the Daytona info because I don’t have any text written in the Forestry page. See attached photo…. We want to be able to add more pics and text on the Winter Park section for Private Parties and Catering. Maybe up to 6 photos with corresponding text? If we add text and photos it shows up, but if we leave it blank nothing shows up.

Also, review access to photos

**Comment by budparr** [comment]
@regisphilibert Would you mind setting up the CMS for the work you did here: https://github.com/theNewDynamic/cocina214.com/issues/14#issuecomment-976835366

dawns on me that I'm not 100% sure what the field should look like with your code.

I set up a branch in Forestry: https://app.forestry.io/sites/krlyk56lr4lohg/#/pages/content-dine-md/

the field would be used on the Dine page. It's the events block at the end of the row of blocks

**Comment by regisphilibert** [comment]
It's all good!

**Comment by budparr** [comment]
Thanks! I'll take it from here (still need some adjustments, but this helps a lot)
