### ISSUE TITLE
Update to latest Snipcart

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/cocina214.com-archive-hugo#16]
I can't figure out why Snipcart is not loading now. I see from the console that transactions are hitting the cart, but the cart's not loading. I found two images with the wrong paths that were not loading, but that hasn't helped either. 

- Snipcart cart icon does not render except when an item is added to the cart (this is [expected behavior](https://github.com/theNewDynamic/cocina214.com/blob/main/layouts/partials/nav.html#L19), I believe)
- Snipcart cart loads items to cart (icon shows number of items) as expected.

- [x] Snipcart checkout does not load when clicking on the icon.

**Comment by regisphilibert** [comment]
We have a deploy preview #17 @budparr . I made sure everything works including the t-shirt with diff sizes.
