### ISSUE TITLE
Find a way to forward old menus to the new

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/cocina214.com-archive-hugo#24]
Client posts PDFs of menus on the site and they are picked up by external sources (foursquare, google, I think).

We need a way for them to update their menu, delete the old version so it's not hanging out there, and make sure that any old links go to the new one. I thought about keeping them all the same name, but then cached versions would be out there.

<details><summary>Details from client</summary>

So I guess what happens is when we upload a new dine menu on the “Dine Page” it creates a link for that menu and never deletes it when we upload a new menu? We change our menus once or twice a year, so what the best way to delete those old links? Is it something I can do? That way when I upload a new menu I know to go delete the old one.
 
We will uploading some new menus next week so I will need those current ones deleted when I make those changes.
 
All of these are old and can be deleted:
 
AfterDinner_5x7_Aug 2018_Final.pdf
AfterDinner_5x7_Dec 2019.pdf
AfterDinner_5x7_Nov 2019.pdf
afterdinner_feb-2021.pdf
AfterDinner_FINAL 2017.pdf
afterdinner_june-2021.pdf
CateringMenu_Aug 2019.pdf
CateringMenu_Jan 2019.pdf
cateringmenu_march-2021.pdf
CateringMenu_Nov 2019.pdf
cateringmenu_sept-2020.pdf
Cocina 214 Menu - August 2019.pdf
Cocina 214 Menu - Dec 2019.pdf
Cocina 214 Menu - Jan 2020.pdf
Cocina 214 Menu - New 2020_letter size_final-1.pdf
Cocina 214 Menu - New 2020_letter size_final.pdf
cocina-214-menu-feb-2021.pdf
cocina-214-menu-june-2021.pdf
cocina-214-menu-october-2021.pdf
cocina-214-menu-sept-2020_legal-size_final.pdf
cocina-214-menu-sept-2020_legal-size_final.pdf
Drinks April 2019.pdf
Drinks August 2018_Final.pdf
Drinks_Long_FINAL 10-5-2017.pdf
drinks-february-2021.pdf
drinks-jan-2020.pdf
drinks-june-2021.pdf
drinks-june-2021.pdf
drinks-sept-2020.pdf
happyhour_5by7_sept-2020.pdf
HappyHour_5x7_April 2019.pdf
HappyHour_5x7_Aug 2018_Final-1.pdf
HappyHour_5x7_Aug 2018_Final-2.pdf
HappyHour_5x7_Aug 2018_Final.pdf
kids_menu_2021.pdf
Kids_Menu_Cocina 2018 Final.pdf
Kids_Menu_Cocina Aug 2018.pdf
PrivateDining_Cocina 214 WP 2018-1.pdf
PrivateDining_Cocina 214 WP 2018.pdf
PrivateDining_WP 2019.pdf
PrivateDining_WP 2020.pdf
privatedining_wp-february-2021.pdf
privatedining_wp-july-2021.pdf
privatedining_wp-sept-10-2021_wo-2021-awards.pdf
privatedining_wp-september-2020.pdf
StandardMenu_August_2018 Final.pdf
StandardMenu_January_2019_FINAL.pdf
TakeOut_Menu_Aug 2018_Final.pdf
TakeOut_Menu_Jan 2019_Final.pdf
TakeOut_Menu_Jan 2020.pdf
TakeOut_Menu_Nov 2019.pdf
</details>

**Comment by regisphilibert** [comment]
If wonder if we could not make those menus associated with pages. It seems menus are linked to events (and maybe meals: breakfast, lunch, diner). IN any case we could ave /:event/menu redirect to a given PDF. By using redirect we won't be worrying about Google indexing the menus or will we?

**Comment by budparr** [comment]
well I think they may put it in various places, and part of the issue is that outside apps apparently pick it up
