### ISSUE TITLE
Update colors on external ordering site

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/cocina214.com-archive-hugo#27]
There are a few colors that need to change to match the existing [site](https://cocina214.com/)

This is the page that needs to change: https://cocina214.alohaorderonline.com

This is the admin page to update things: https://nolo-adminweb-nua.ncrsaas.com/Login.aspx

The log-in credentials are in 1pW: "Alohaorderonline Cocina214"

I've pulled our colors from the site's CSS file:

```
:root {
  --magenta: rgba(148, 78, 129, 1);
  --magenta-light: #cea1c2;
  --magenta-dark: #452c4d;
  --olympus-green: rgba(62, 89, 92, 1); / #3e595c
  --olympus-green-light: #79A0A4;
  --olympus-green-lighter: #96d6dd;
  
  --olympus-green-dark: #354C4E;
  --lady-liberty: rgba(150, 210, 183, 1);
  --lady-liberty-dark: #4a6a5c;
  --lady-liberty-light: #B1E9D0;
  --pink-ladies: rgba(222, 123, 166, 1); 
  --pink-ladies-dark: #A5597A; 
  /* PINK LADIES DE7BA6 */
}
```
client direction: 
replace the Orange with the Olympus Green color, replace the Red with the Magenta (it looks more purple than Magenta) and replace the Tan with Liberty Green.

The user manual, in case it's not intuitive: 
[AlohaOnline - User Guide - v20.8.pdf](https://github.com/theNewDynamic/cocina214.com/files/8042471/AlohaOnline.-.User.Guide.-.v20.8.pdf)

**Comment by AdamChlan** [comment]
@budparr I believe this is in good shape

**Comment by budparr** [comment]
Never heard back from the client, so we'll assume they're happy!
